title: "SIADS697 Project Documentation"
description: "Documenting procedures and results related to MADS Capstone Project."
remote_theme: pmarsceill/just-the-docs
search_enabled: true
aux_links:
  "GitHub Repository":
    - "https://github.com/albemlee/siads697"
aux_links_new_tab: true
markdown: kramdown
back_to_top: true
back_to_top_text: "Back to top"
footer_content: "For more information about the project, you may reach out to <a href=\"jcreigh@umich.edu\">Jim Creighton</a>, <a href=\"albemlee@umich.edu\">Albert Lee</a>m or <a href=\"jcreigh@umich.edu\"><a href=\"maxts@umich.edu\">Max Tsisyk</a></a>"
